import { useState, useEffect, useRef } from 'react';
import { motion, useScroll, useTransform, useInView, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import { 
  Activity, 
  Brain, 
  BarChart3, 
  Zap, 
  Target, 
  TrendingUp,
  ChevronRight,
  Play,
  Users,
  Award,
  Calendar,
  Heart,
  MessageCircle,
  Trophy,
  Dumbbell,
  Timer,
  Flame,
  Star,
  Check,
  ArrowRight
} from 'lucide-react';
import { Button, AnimatedCounter } from '../components/ui';

// Animated particles for hero section
const FloatingParticle = ({ delay, duration, size, color }) => (
  <motion.div
    className={`absolute rounded-full ${color}`}
    style={{ width: size, height: size }}
    initial={{ opacity: 0, y: 100, x: Math.random() * 100 - 50 }}
    animate={{ 
      opacity: [0, 1, 1, 0],
      y: [-20, -200],
      x: [0, Math.random() * 100 - 50]
    }}
    transition={{ 
      duration, 
      delay, 
      repeat: Infinity,
      ease: "easeOut"
    }}
  />
);

// Animated gradient orb
const GradientOrb = ({ className, delay = 0 }) => (
  <motion.div
    className={`absolute rounded-full blur-[100px] ${className}`}
    animate={{ 
      scale: [1, 1.2, 1],
      opacity: [0.3, 0.5, 0.3]
    }}
    transition={{ duration: 8, delay, repeat: Infinity }}
  />
);

export default function LandingPage() {
  const { scrollY } = useScroll();
  const heroOpacity = useTransform(scrollY, [0, 400], [1, 0]);
  const heroScale = useTransform(scrollY, [0, 400], [1, 0.9]);
  const heroY = useTransform(scrollY, [0, 400], [0, 100]);
  
  const [activeTestimonial, setActiveTestimonial] = useState(0);
  
  // Auto-rotate testimonials
  useEffect(() => {
    const interval = setInterval(() => {
      setActiveTestimonial(prev => (prev + 1) % 3);
    }, 5000);
    return () => clearInterval(interval);
  }, []);
  
  // Stats for counter
  const stats = [
    { value: 50000, label: 'Active Athletes', suffix: '+', icon: Users },
    { value: 2.5, label: 'Million Workouts', suffix: 'M', icon: Activity },
    { value: 98, label: 'Satisfaction Rate', suffix: '%', icon: Star },
    { value: 15, label: 'Avg. Performance Gain', suffix: '%', prefix: '+', icon: TrendingUp },
  ];
  
  // Features - based on actual app capabilities
  const features = [
    {
      icon: Activity,
      title: 'Smart Workout Logging',
      description: 'Log runs, weightlifting, cardio, and biometrics. Import from Strava, Garmin, and more.',
      color: 'from-cyan-500 to-blue-500',
      preview: '🏃 Running • 🏋️ Weights • ❤️ Cardio • 📊 Biometrics'
    },
    {
      icon: Brain,
      title: 'AI Training Plans',
      description: 'Get personalized weekly training schedules generated by AI based on your history.',
      color: 'from-purple-500 to-pink-500',
      preview: '🤖 Auto-Generated • 📅 Weekly Plans • 💪 Personalized'
    },
    {
      icon: BarChart3,
      title: 'Advanced Analytics',
      description: 'Interactive charts, training load heatmaps, and performance trend visualization.',
      color: 'from-orange-500 to-red-500',
      preview: '📈 Charts • 🗓️ Heatmaps • 📊 Trends'
    },
    {
      icon: Target,
      title: 'Goal Tracking',
      description: 'Set distance, duration, workout frequency goals with progress tracking and milestones.',
      color: 'from-green-500 to-emerald-500',
      preview: '🎯 Set Goals • 📈 Track Progress • 🏆 Earn Badges'
    },
    {
      icon: Users,
      title: 'Social Network',
      description: 'Follow friends, share workouts, react with 💪🔥⚡, and climb the leaderboard.',
      color: 'from-blue-500 to-indigo-500',
      preview: '👥 Activity Feed • 🏆 Leaderboards • 💬 Comments'
    },
    {
      icon: Award,
      title: 'Badges & Achievements',
      description: 'Earn badges for streaks, distance PRs, workout milestones, and more.',
      color: 'from-yellow-500 to-orange-500',
      preview: '🏅 50+ Badges • 🔥 Streaks • 🎖️ Rare Awards'
    },
  ];
  
  const testimonials = [
    {
      quote: "This app transformed my training. The AI insights helped me break my marathon PR by 8 minutes!",
      author: "Sarah K.",
      role: "Marathon Runner",
      avatar: "🏃‍♀️",
      stat: "-8 min PR"
    },
    {
      quote: "The social features keep me accountable. Seeing my friends' workouts motivates me to stay consistent.",
      author: "Mike T.",
      role: "CrossFit Athlete",
      avatar: "🏋️",
      stat: "365 day streak"
    },
    {
      quote: "Finally, an app that understands periodization. The recovery score saved me from overtraining.",
      author: "Emma L.",
      role: "Triathlete",
      avatar: "🏊",
      stat: "98% injury-free"
    }
  ];
  
  return (
    <div className="min-h-screen bg-dark-500 overflow-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass-strong backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <motion.div 
              className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-lime-500 flex items-center justify-center"
              whileHover={{ scale: 1.1, rotate: 5 }}
            >
              <Activity className="w-6 h-6 text-dark-500" />
            </motion.div>
            <span className="text-xl font-bold gradient-text hidden sm:block">SportTrack AI</span>
          </Link>
          
          <div className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-gray-300 hover:text-white transition-colors">Features</a>
            <a href="#social" className="text-gray-300 hover:text-white transition-colors">Social</a>
            <a href="#testimonials" className="text-gray-300 hover:text-white transition-colors">Athletes</a>
          </div>
          
          <div className="flex items-center gap-3">
            <Link to="/login">
              <Button variant="ghost" size="sm">Sign In</Button>
            </Link>
            <Link to="/register">
              <Button size="sm">Get Started</Button>
            </Link>
          </div>
        </div>
      </nav>
      
      {/* Hero Section */}
      <motion.section 
        style={{ opacity: heroOpacity, scale: heroScale, y: heroY }}
        className="relative min-h-screen flex items-center justify-center pt-20 overflow-hidden"
      >
        {/* Animated Background */}
        <div className="absolute inset-0">
          <GradientOrb className="top-1/4 -left-40 w-[600px] h-[600px] bg-primary-500/30" />
          <GradientOrb className="bottom-1/4 -right-40 w-[500px] h-[500px] bg-lime-500/20" delay={2} />
          <GradientOrb className="top-1/2 left-1/2 -translate-x-1/2 w-[400px] h-[400px] bg-purple-500/10" delay={4} />
        </div>
        
        {/* Animated Grid */}
        <div className="absolute inset-0 opacity-20">
          <motion.div 
            className="absolute inset-0"
            animate={{ backgroundPosition: ['0% 0%', '100% 100%'] }}
            transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}
            style={{
              backgroundImage: `
                linear-gradient(rgba(0, 212, 255, 0.1) 1px, transparent 1px),
                linear-gradient(90deg, rgba(0, 212, 255, 0.1) 1px, transparent 1px)
              `,
              backgroundSize: '60px 60px'
            }} 
          />
        </div>
        
        {/* Floating Particles */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          {[...Array(8)].map((_, i) => (
            <FloatingParticle
              key={i}
              delay={i * 0.8}
              duration={4 + Math.random() * 2}
              size={4 + Math.random() * 8}
              color={i % 2 === 0 ? 'bg-primary-500/50' : 'bg-lime-500/50'}
            />
          ))}
        </div>
        
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 text-center">
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-8"
          >
            <motion.span 
              className="w-2 h-2 rounded-full bg-lime-500"
              animate={{ scale: [1, 1.5, 1], opacity: [1, 0.5, 1] }}
              transition={{ duration: 2, repeat: Infinity }}
            />
            <span className="text-sm text-gray-300">Your AI-Powered Fitness Companion</span>
          </motion.div>
          
          {/* Main Headline with Animated Words */}
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="text-4xl sm:text-5xl md:text-7xl lg:text-8xl font-black mb-6 leading-tight"
          >
            <motion.span 
              className="text-white inline-block"
              animate={{ y: [0, -5, 0] }}
              transition={{ duration: 3, repeat: Infinity }}
            >
              Track.
            </motion.span>
            {' '}
            <motion.span 
              className="text-white inline-block"
              animate={{ y: [0, -5, 0] }}
              transition={{ duration: 3, delay: 0.2, repeat: Infinity }}
            >
              Analyze.
            </motion.span>
            {' '}
            <motion.span 
              className="gradient-text inline-block"
              animate={{ y: [0, -5, 0] }}
              transition={{ duration: 3, delay: 0.4, repeat: Infinity }}
            >
              Dominate.
            </motion.span>
          </motion.h1>
          
          {/* Subtitle */}
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="text-lg sm:text-xl text-gray-400 max-w-2xl mx-auto mb-10"
          >
            The ultimate training platform for serious athletes. AI insights, social accountability, 
            and powerful analytics to unlock your peak performance.
          </motion.p>
          
          {/* CTA Buttons */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16"
          >
            <Link to="/register">
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Button size="lg" icon={Zap} className="shadow-glow-md">
                  Start Training Free
                </Button>
              </motion.div>
            </Link>
            <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
              <Button variant="secondary" size="lg" icon={Play}>
                Watch Demo
              </Button>
            </motion.div>
          </motion.div>
          
          {/* Live Activity Preview */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7, duration: 0.8 }}
            className="relative max-w-5xl mx-auto"
          >
            <div className="glass rounded-3xl p-2 sm:p-4 shadow-2xl border border-white/10">
              <div className="bg-dark-400 rounded-2xl overflow-hidden">
                {/* App Header */}
                <div className="border-b border-white/5 px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between">
                  <div className="flex items-center gap-2 sm:gap-3">
                    <div className="w-2.5 sm:w-3 h-2.5 sm:h-3 rounded-full bg-crimson-500" />
                    <div className="w-2.5 sm:w-3 h-2.5 sm:h-3 rounded-full bg-orange-500" />
                    <div className="w-2.5 sm:w-3 h-2.5 sm:h-3 rounded-full bg-lime-500" />
                  </div>
                  <div className="text-xs sm:text-sm text-gray-500">Live Dashboard</div>
                  <div className="flex items-center gap-2">
                    <motion.div
                      animate={{ scale: [1, 1.2, 1] }}
                      transition={{ duration: 2, repeat: Infinity }}
                      className="w-2 h-2 rounded-full bg-lime-500"
                    />
                    <span className="text-xs text-lime-500">Live</span>
                  </div>
                </div>
                
                {/* Dashboard Grid */}
                <div className="p-4 sm:p-6 grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
                  {/* Recovery Score */}
                  <motion.div 
                    className="col-span-1 bg-gradient-to-br from-lime-500/10 to-green-500/10 rounded-xl p-3 sm:p-4 border border-lime-500/20"
                    whileHover={{ scale: 1.02 }}
                  >
                    <div className="text-xs sm:text-sm text-gray-400 mb-1 sm:mb-2">Recovery Score</div>
                    <div className="text-3xl sm:text-4xl font-bold text-lime-500">92</div>
                    <div className="text-xs text-lime-500/70 mt-1">Ready to train hard</div>
                  </motion.div>
                  
                  {/* Weekly Stats */}
                  <motion.div 
                    className="col-span-1 bg-dark-300/50 rounded-xl p-3 sm:p-4"
                    whileHover={{ scale: 1.02 }}
                  >
                    <div className="text-xs sm:text-sm text-gray-400 mb-1">This Week</div>
                    <div className="text-2xl sm:text-3xl font-bold text-white">6 <span className="text-base sm:text-lg text-gray-500">workouts</span></div>
                    <div className="text-xs text-primary-500 mt-1">🔥 On fire!</div>
                  </motion.div>
                  
                  {/* Distance */}
                  <motion.div 
                    className="col-span-1 bg-dark-300/50 rounded-xl p-3 sm:p-4"
                    whileHover={{ scale: 1.02 }}
                  >
                    <div className="text-xs sm:text-sm text-gray-400 mb-1">Distance</div>
                    <div className="text-2xl sm:text-3xl font-bold text-white">48.5 <span className="text-base sm:text-lg text-gray-500">km</span></div>
                    <div className="text-xs text-orange-500 mt-1">+12% vs last week</div>
                  </motion.div>
                  
                  {/* Time */}
                  <motion.div 
                    className="col-span-1 bg-dark-300/50 rounded-xl p-3 sm:p-4"
                    whileHover={{ scale: 1.02 }}
                  >
                    <div className="text-xs sm:text-sm text-gray-400 mb-1">Active Time</div>
                    <div className="text-2xl sm:text-3xl font-bold text-white">9.2 <span className="text-base sm:text-lg text-gray-500">hrs</span></div>
                    <div className="text-xs text-purple-500 mt-1">Personal best!</div>
                  </motion.div>
                  
                  {/* Activity Chart */}
                  <div className="col-span-2 lg:col-span-4 bg-dark-300/30 rounded-xl p-3 sm:p-4 h-28 sm:h-36">
                    <div className="text-xs sm:text-sm text-gray-400 mb-2 sm:mb-3">Weekly Activity</div>
                    <div className="flex items-end justify-between h-16 sm:h-20 gap-1 sm:gap-2">
                      {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, i) => {
                        const heights = [45, 75, 30, 90, 65, 85, 55];
                        return (
                          <div key={day} className="flex-1 flex flex-col items-center gap-1 sm:gap-2">
                            <motion.div
                              initial={{ height: 0 }}
                              animate={{ height: `${heights[i]}%` }}
                              transition={{ delay: 1 + i * 0.1, duration: 0.5 }}
                              className="w-full rounded-t-lg bg-gradient-to-t from-primary-500/50 to-primary-500"
                            />
                            <span className="text-[10px] sm:text-xs text-gray-500">{day[0]}</span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Floating Cards */}
            <motion.div
              animate={{ y: [-10, 10, -10] }}
              transition={{ duration: 4, repeat: Infinity }}
              className="absolute -top-4 sm:-top-6 -right-4 sm:-right-8 glass rounded-xl p-3 sm:p-4 shadow-lg z-20 hidden sm:block"
            >
              <div className="flex items-center gap-2 sm:gap-3">
                <div className="w-8 sm:w-10 h-8 sm:h-10 rounded-full bg-yellow-500/20 flex items-center justify-center">
                  <Award className="w-4 sm:w-5 h-4 sm:h-5 text-yellow-500" />
                </div>
                <div>
                  <div className="text-xs sm:text-sm text-gray-400">New Badge!</div>
                  <div className="text-sm sm:text-base font-bold text-white">🏃 10K Club</div>
                </div>
              </div>
            </motion.div>
            
            <motion.div
              animate={{ y: [10, -10, 10] }}
              transition={{ duration: 5, repeat: Infinity }}
              className="absolute -bottom-4 sm:-bottom-6 -left-4 sm:-left-8 glass rounded-xl p-3 sm:p-4 shadow-lg z-20 hidden sm:block"
            >
              <div className="flex items-center gap-2 sm:gap-3">
                <div className="w-8 sm:w-10 h-8 sm:h-10 rounded-full bg-primary-500/20 flex items-center justify-center">
                  <Brain className="w-4 sm:w-5 h-4 sm:h-5 text-primary-500" />
                </div>
                <div>
                  <div className="text-xs sm:text-sm text-gray-400">AI Insight</div>
                  <div className="text-xs sm:text-sm font-medium text-white">Ready for tempo run</div>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </div>
        
        {/* Scroll indicator */}
        <motion.div
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
          className="absolute bottom-8 left-1/2 -translate-x-1/2"
        >
          <div className="w-6 h-10 rounded-full border-2 border-white/20 flex justify-center pt-2">
            <motion.div
              animate={{ opacity: [0.5, 1, 0.5], y: [0, 8, 0] }}
              transition={{ duration: 2, repeat: Infinity }}
              className="w-1.5 h-1.5 rounded-full bg-primary-500"
            />
          </div>
        </motion.div>
      </motion.section>
      
      {/* Stats Section */}
      <section id="stats" className="py-20 sm:py-24 relative border-t border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="grid grid-cols-2 md:grid-cols-4 gap-6 sm:gap-8"
          >
            {stats.map((stat, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="text-center group"
              >
                <motion.div 
                  className="w-12 sm:w-14 h-12 sm:h-14 mx-auto mb-3 sm:mb-4 rounded-2xl bg-gradient-to-br from-primary-500/20 to-lime-500/20 flex items-center justify-center"
                  whileHover={{ scale: 1.1, rotate: 5 }}
                >
                  <stat.icon className="w-6 sm:w-7 h-6 sm:h-7 text-primary-500" />
                </motion.div>
                <div className="text-3xl sm:text-4xl md:text-5xl font-black gradient-text mb-1 sm:mb-2">
                  <AnimatedCounter 
                    value={stat.value} 
                    prefix={stat.prefix}
                    suffix={stat.suffix}
                    decimals={stat.value < 10 ? 1 : 0}
                  />
                </div>
                <div className="text-sm sm:text-base text-gray-400">{stat.label}</div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>
      
      {/* Features Section */}
      <section id="features" className="py-20 sm:py-24 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-primary-500/5 to-transparent" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12 sm:mb-16"
          >
            <motion.div 
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-6"
              whileHover={{ scale: 1.05 }}
            >
              <Flame className="w-4 h-4 text-orange-500" />
              <span className="text-sm text-gray-300">Everything You Need</span>
            </motion.div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black mb-4">
              <span className="gradient-text">Powerful Features</span>
            </h2>
            <p className="text-gray-400 text-base sm:text-lg max-w-2xl mx-auto">
              Built for athletes who demand the best. Every feature designed to help you reach your peak.
            </p>
          </motion.div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -5, scale: 1.02 }}
                className="glass rounded-2xl p-5 sm:p-6 group cursor-pointer border border-white/5 hover:border-white/20 transition-all duration-300"
              >
                <motion.div 
                  className={`w-12 sm:w-14 h-12 sm:h-14 rounded-2xl mb-4 sm:mb-5 flex items-center justify-center bg-gradient-to-br ${feature.color}`}
                  whileHover={{ scale: 1.1, rotate: 5 }}
                >
                  <feature.icon className="w-6 sm:w-7 h-6 sm:h-7 text-white" />
                </motion.div>
                <h3 className="text-lg sm:text-xl font-bold text-white mb-2">{feature.title}</h3>
                <p className="text-gray-400 text-sm sm:text-base mb-3 sm:mb-4">{feature.description}</p>
                <div className="text-xs text-gray-500 bg-dark-300/50 rounded-lg px-3 py-2">
                  {feature.preview}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Social Section */}
      <section id="social" className="py-20 sm:py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-primary-500/10 via-transparent to-lime-500/10" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 relative z-10">
          <div className="grid lg:grid-cols-2 gap-8 sm:gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-6">
                <Users className="w-4 h-4 text-blue-500" />
                <span className="text-sm text-gray-300">Built-in Social Network</span>
              </div>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-black mb-4 sm:mb-6">
                Train Together.<br />
                <span className="gradient-text">Compete Together.</span>
              </h2>
              <p className="text-gray-400 text-base sm:text-lg mb-6 sm:mb-8">
                Connect with athletes worldwide. Share your achievements, react with 💪🔥⚡🎯❤️, 
                compete on leaderboards, and stay motivated together.
              </p>
              <div className="grid grid-cols-2 gap-4">
                {[
                  { icon: Heart, label: 'React to Posts', value: '5 Reactions' },
                  { icon: MessageCircle, label: 'Comments', value: 'Real-time' },
                  { icon: Trophy, label: 'Leaderboards', value: 'Weekly/Monthly' },
                  { icon: Award, label: 'Badges', value: '50+ to Earn' },
                ].map((item, i) => (
                  <motion.div
                    key={i}
                    whileHover={{ scale: 1.05 }}
                    className="glass rounded-xl p-3 sm:p-4"
                  >
                    <item.icon className="w-5 h-5 text-primary-500 mb-2" />
                    <div className="text-xs sm:text-sm text-gray-400">{item.label}</div>
                    <div className="text-sm sm:text-base font-bold text-white">{item.value}</div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
            
            {/* Mock Feed */}
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="glass rounded-2xl p-4 sm:p-6"
            >
              <div className="flex items-center gap-2 mb-4 sm:mb-6">
                <Activity className="w-5 h-5 text-primary-500" />
                <span className="font-semibold text-white">Activity Feed</span>
              </div>
              
              {[
                { user: 'Alex M.', action: 'completed a 10K run', time: '2m ago', emoji: '🏃', reactions: '💪 12' },
                { user: 'Sarah K.', action: 'earned Marathon Ready badge', time: '15m ago', emoji: '🏅', reactions: '🔥 24' },
                { user: 'Mike T.', action: 'logged 5x5 strength workout', time: '1h ago', emoji: '🏋️', reactions: '💪 8' },
              ].map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: 20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.2 + i * 0.1 }}
                  className="flex items-start gap-3 p-3 rounded-xl bg-dark-300/30 mb-3"
                >
                  <div className="w-9 sm:w-10 h-9 sm:h-10 rounded-full bg-gradient-to-br from-primary-500/20 to-lime-500/20 flex items-center justify-center text-lg sm:text-xl">
                    {item.emoji}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-white">
                      <span className="font-bold">{item.user}</span> {item.action}
                    </p>
                    <div className="flex items-center gap-3 mt-1">
                      <span className="text-xs text-gray-500">{item.time}</span>
                      <span className="text-xs bg-dark-400/50 px-2 py-0.5 rounded-full">{item.reactions}</span>
                    </div>
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>
      
      {/* Testimonials */}
      <section id="testimonials" className="py-20 sm:py-24 relative">
        <div className="max-w-5xl mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-10 sm:mb-12"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black mb-4">
              Loved by <span className="gradient-text">Athletes</span>
            </h2>
          </motion.div>
          
          <div className="relative">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeTestimonial}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.5 }}
                className="glass rounded-3xl p-6 sm:p-10 text-center"
              >
                <div className="text-5xl sm:text-6xl mb-4 sm:mb-6">{testimonials[activeTestimonial].avatar}</div>
                <blockquote className="text-lg sm:text-xl md:text-2xl text-white mb-6 sm:mb-8 max-w-3xl mx-auto leading-relaxed">
                  "{testimonials[activeTestimonial].quote}"
                </blockquote>
                <div className="flex items-center justify-center gap-4 sm:gap-6">
                  <div>
                    <div className="font-bold text-white">{testimonials[activeTestimonial].author}</div>
                    <div className="text-sm text-gray-400">{testimonials[activeTestimonial].role}</div>
                  </div>
                  <div className="w-px h-10 bg-white/20" />
                  <div className="text-xl sm:text-2xl font-bold gradient-text">
                    {testimonials[activeTestimonial].stat}
                  </div>
                </div>
              </motion.div>
            </AnimatePresence>
            
            {/* Dots */}
            <div className="flex justify-center gap-2 mt-6 sm:mt-8">
              {testimonials.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setActiveTestimonial(i)}
                  className={`w-2.5 sm:w-3 h-2.5 sm:h-3 rounded-full transition-all ${
                    i === activeTestimonial ? 'bg-primary-500 w-6 sm:w-8' : 'bg-white/20 hover:bg-white/40'
                  }`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>
      
      {/* Final CTA */}
      <section className="py-20 sm:py-24 relative">
        <div className="absolute inset-0">
          <GradientOrb className="top-0 left-1/4 w-[500px] h-[500px] bg-lime-500/20" />
          <GradientOrb className="bottom-0 right-1/4 w-[400px] h-[400px] bg-primary-500/20" delay={2} />
        </div>
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <motion.div
              animate={{ rotate: [0, 5, -5, 0] }}
              transition={{ duration: 4, repeat: Infinity }}
              className="inline-block text-5xl sm:text-6xl mb-6"
            >
              🏆
            </motion.div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black mb-4 sm:mb-6">
              Ready to <span className="gradient-text">Level Up</span> Your Training?
            </h2>
            <p className="text-gray-400 text-base sm:text-lg mb-8 sm:mb-10 max-w-2xl mx-auto">
              Join thousands of athletes who've transformed their performance with AI-powered insights 
              and social accountability.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link to="/register">
                <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                  <Button size="xl" icon={ArrowRight} iconPosition="right" className="shadow-glow-lg">
                    Start Free Today
                  </Button>
                </motion.div>
              </Link>
              <div className="flex items-center gap-2 text-gray-400 text-sm">
                <Check className="w-4 h-4 text-lime-500" />
                <span>No credit card required</span>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="border-t border-white/5 py-8 sm:py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary-500 to-lime-500 flex items-center justify-center">
                <Activity className="w-4 h-4 text-dark-500" />
              </div>
              <span className="font-bold text-white">SportTrack AI</span>
            </div>
            <div className="flex items-center gap-6 text-sm text-gray-500">
              <a href="#" className="hover:text-white transition-colors">Privacy</a>
              <a href="#" className="hover:text-white transition-colors">Terms</a>
              <a href="#" className="hover:text-white transition-colors">Contact</a>
            </div>
            <p className="text-gray-500 text-sm">
              © 2024 SportTrack AI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
